#!/bin/sh

# Inject environment variables into config.js
cat <<EOF > /usr/share/nginx/html/config.js
window.__CONFIG__ = {
  APP_BACKEND_URI: "${VITE_APP_BACKEND_URI}",
  APP_WS_BACKEND_URI: "${VITE_APP_WS_BACKEND_URI}",
  APP_VERSION: "${VITE_APP_VERSION}",
  AUTO_UPDATE_BUTTON_REFRESH_RATE_SECONDS: ${VITE_AUTO_UPDATE_BUTTON_REFRESH_RATE_SECONDS},
  DASHBOARD_DATA_REFRESH_RATE_SECONDS: ${VITE_DASHBOARD_DATA_REFRESH_RATE_SECONDS},
  DUT_LOCAL_TIME_REPORT_RATE_SECONDS: ${VITE_DUT_LOCAL_TIME_REPORT_RATE_SECONDS},
  REFRESH_APPLY_STATUS_INTERVAL_SECONDS: ${VITE_REFRESH_APPLY_STATUS_INTERVAL_SECONDS},
  IDLE_LOGOUT_TIMEOUT_MINUTES: ${VITE_IDLE_LOGOUT_TIMEOUT_MINUTES}
};
EOF

# Start Nginx
exec nginx -g "daemon off;"
