import { BGW_EVENT_ACTIONS } from 'constant'
import {
  getWireless2Primary,
  updateWireless2Primary,
  updateWireless2PrimaryStatus,
  getWireless5Primary,
  updateWireless5Primary,
  updateWireless5PrimaryStatus,
  getWireless2Multiple,
  updateWireless2Multiple,
  getWireless5Multiple,
  updateWireless5Multiple,
} from 'reducers/bgw5105/wireless'

export const getWireless = {
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_PRIMARY_SSID_CONFIG]:
    getWireless2Primary,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_PRIMARY_SSID_WIFI_STATUS]:
    updateWireless2PrimaryStatus,

  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_MULTIPLE_SSID_1_CONFIG]:
    getWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_MULTIPLE_SSID_2_CONFIG]:
    getWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_MULTIPLE_SSID_3_CONFIG]:
    getWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_MULTIPLE_SSID_4_CONFIG]:
    getWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_MULTIPLE_SSID_5_CONFIG]:
    getWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_MULTIPLE_SSID_6_CONFIG]:
    getWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_GET_MULTIPLE_SSID_7_CONFIG]:
    getWireless2Multiple,

  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_PRIMARY_SSID_CONFIG]:
    getWireless5Primary,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_PRIMARY_SSID_WIFI_STATUS]:
    updateWireless5PrimaryStatus,

  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_MULTIPLE_SSID_1_CONFIG]:
    getWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_MULTIPLE_SSID_2_CONFIG]:
    getWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_MULTIPLE_SSID_3_CONFIG]:
    getWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_MULTIPLE_SSID_4_CONFIG]:
    getWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_MULTIPLE_SSID_5_CONFIG]:
    getWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_MULTIPLE_SSID_6_CONFIG]:
    getWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_GET_MULTIPLE_SSID_7_CONFIG]:
    getWireless5Multiple,
}
export const updateWireless = {
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_SET_PRIMARY_SSID_CONFIG]:
    updateWireless2Primary,

  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_SET_MULTIPLE_SSID_1_CONFIG]:
    updateWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_SET_MULTIPLE_SSID_2_CONFIG]:
    updateWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_SET_MULTIPLE_SSID_3_CONFIG]:
    updateWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_SET_MULTIPLE_SSID_4_CONFIG]:
    updateWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_SET_MULTIPLE_SSID_5_CONFIG]:
    updateWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_SET_MULTIPLE_SSID_6_CONFIG]:
    updateWireless2Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_TWO_POINT_FOUR_GHZ_SET_MULTIPLE_SSID_7_CONFIG]:
    updateWireless2Multiple,

  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_SET_PRIMARY_SSID_CONFIG]:
    updateWireless5Primary,

  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_SET_MULTIPLE_SSID_1_CONFIG]:
    updateWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_SET_MULTIPLE_SSID_2_CONFIG]:
    updateWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_SET_MULTIPLE_SSID_3_CONFIG]:
    updateWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_SET_MULTIPLE_SSID_4_CONFIG]:
    updateWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_SET_MULTIPLE_SSID_5_CONFIG]:
    updateWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_SET_MULTIPLE_SSID_6_CONFIG]:
    updateWireless5Multiple,
  [BGW_EVENT_ACTIONS.WIRELESS_FIVE_GHZ_SET_MULTIPLE_SSID_7_CONFIG]:
    updateWireless5Multiple,
}
